### ISSUE TITLE
install fails to compile

### ISSUE THREAD

**Issue by mark-rodgers** [notjosh/bleno-mac#3]
Can't install bleno-mac :(

I can install noble-mac fine using the same command, which from what I read sounds like this is just a fork of that then modified to be used for peripherals instead of central. So I'm thinking maybe there is a bug somewhere in this package.

### Environment

os: macOS Mojave (10.14.2)
node: 10.14.2
node-gyp: 3.8.0
npm: 6.4.1

### Command Issued

`npm i github:notjosh/bleno-mac`

### Error Log

```
> bleno-mac@0.0.1 install /Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/notjosh/bleno-mac/releases/download/0.0.1/bleno_mac-v0.0.1-node-v64-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for bleno-mac@0.0.1 and node@10.14.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Pre-built binaries not installable for bleno-mac@0.0.1 and node@10.14.2 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Connection closed while downloading tarball file
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
rm: ./Release/.deps/Release/obj.target/nothing/../node-addon-api/src/nothing.o.d.raw: No such file or directory
make: *** [Release/obj.target/nothing/../node-addon-api/src/nothing.o] Error 1
gyp  LIBTOOL-STATIC Release/nothing.a
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node@10/10.14.2/bin/node" "/usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node" "--module_name=bleno_mac" "--module_path=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node@10/10.14.2/bin/node /usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node --module_name=bleno_mac --module_path=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/mark-rodgers/Projects/playground/nodehu/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node@10/10.14.2/bin/node" "/Users/mark-rodgers/Projects/playground/nodehu/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac
node-pre-gyp ERR! node -v v10.14.2
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node@10/10.14.2/bin/node /usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node --module_name=bleno_mac --module_path=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native --napi_version=3 --node_abi_napi=napi' (1)
  SOLINK_MODULE(target) /Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node
clang: error: no such file or directory: 'Release/obj.target/bleno_mac/src/bleno_mac.o'
clang: error: no such file or directory: 'Release/obj.target/bleno_mac/src/napi_objc.o'
clang: error: no such file or directory: 'Release/obj.target/bleno_mac/src/ble_peripheral_manager.o'
clang: error: no such file or directory: 'Release/obj.target/bleno_mac/src/objc_cpp.o'
clang: error: no such file or directory: 'Release/obj.target/bleno_mac/src/callbacks.o'
make: *** [/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node@10/10.14.2/bin/node" "/usr/local/Cellar/node@10/10.14.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native/bleno_mac.node" "--module_name=bleno_mac" "--module_path=/Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac/native" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/mark-rodgers/Projects/playground/nodehu/node_modules/bleno-mac
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bleno-mac@0.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bleno-mac@0.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark-rodgers/.npm/_logs/2018-12-28T18_17_01_916Z-debug.log
```

**Comment by mark-rodgers** [comment]
discard, I cleaned out the package.json on my project and deleted my node_modules and did a fresh install and it is now installing.
